# A containerized Nexus server

FROM ubi8/ubi:8.3

ARG NEXUS_VERSION="2.14.3-02"

ENV NEXUS_HOME="/opt/nexus"

RUN 	yum install -y --setopt=tsflags=nodocs java-1.8.0-openjdk-devel\ 
	&& yum clean all -y

RUN 	groupadd -r nexus -f -g 1001 \
	&& useradd -u 1001 -r -g nexus -m -d ${NEXUS_HOME} \
        -s /sbin/nologin \
        -c "Nexus User" nexus

ADD	nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}
ADD	nexus-start.sh ${NEXUS_HOME}

RUN	chmod -R 755 ${NEXUS_HOME}\
	&& ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2 \
	&& chown -R nexus:nexus ${NEXUS_HOME}

VOLUME	/opt/nexus/sonatype-work

ENTRYPOINT ["/opt/nexus/nexus-start.sh"]

